DROP TABLE IF EXISTS Personagem;
DROP TABLE IF EXISTS Classe;
DROP TABLE IF EXISTS Habilidade;
DROP TABLE IF EXISTS Raca;

CREATE TABLE Raca (
    IDRaca INT IDENTITY PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Descricao VARCHAR(500) NULL,
    Origem VARCHAR(150) NOT NULL,
    Perdido DATETIME NULL,
);

CREATE TABLE Habilidade (
    IDHabilidade INT IDENTITY PRIMARY KEY,
    Nome VARCHAR(200) NOT NULL,
    MultiplicadorPoder INT NULL
);

CREATE TABLE Classe (
    IDClasse INT IDENTITY PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Caracteristicas VARCHAR(1000) NULL,
    IDHabilidade INT FOREIGN KEY REFERENCES Habilidade(IDHabilidade) NULL
);

CREATE TABLE Personagem (
    IDPersonagem INT IDENTITY PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Descricao VARCHAR(500) NULL,
    DataNascimento DATETIME NOT NULL,
    IDClasse INT FOREIGN KEY REFERENCES Classe(IDClasse) NOT NULL,
    IDRaca INT FOREIGN KEY REFERENCES Raca(IDRaca) NOT NULL
);

ALTER TABLE Personagem ADD Poder INT NOT NULL;

ALTER TABLE Classe ALTER COLUMN Caracteristicas VARCHAR(500);

ALTER TABLE Raca DROP COLUMN Perdido;